[project]
authors = [
  { name = "Changjun Lim", email = "changjun.lim0@gmail.com" }
]
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
  "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Graphics"
]
dependencies = [
  "Pillow>=9.2.0",
  "fonttools>=4.0.0"
]
description = "Python wrapper for Pillow (PIL) to create text-heavy images"
license = "MIT"
license-files = [ "LICENSE" ]
name = "pillow-document-writer"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"
urls.Source = "https://github.com/ChangjunLim0/pillow-document-writer"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "pytest",
    "black"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
